from capsule import task


untrusted_code = """
print("This is untrusted code that can be generated by AI")
result = 42
"""


@task(name="executeUntrustedCode", compute="HIGH", timeout="1s")
def execute_untrusted_code():
    local_vars = {}
    exec(untrusted_code, {}, local_vars)
    return local_vars.get("result")


@task(name="main", compute="HIGH", timeout="30s")
def main():
    result = execute_untrusted_code()
    print(f"Result from untrusted code: {result}")
    return result
